<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAll(){
        $query = $this->getEntityManager()->createQuery(
          "SELECT a FROM HearWeGoHearWeGoBundle:Article a ORDER BY a.createdAt DESC"
        );
        return $query->getResult();
    }

    public function findLimit( $num ){
        $query = $this->getEntityManager()->createQuery(
          "SELECT a FROM HearWeGoHearWeGoBundle:Article a ORDER BY a.createdAt DESC"
        )->setMaxResults( $num );
        return $query->getResult();
    }
    public function findById($id)
    {
        return $this->getEntityManager()->createQuery('SELECT a FROM HearWeGoHearWeGoBundle:Article a WHERE a.id=:id')->setParameter('id',$id)->getOneOrNullResult();
    }

    public function findByDestination($id)
    {
        return $this->getEntityManager()->createQuery('SELECT a FROM HearWeGoHearWeGoBundle:Article a WHERE IDENTITY (a.destination)=:id')->setParameter('id',$id)->getResult();
    }

    public function findRelativeArticle($id)
    {
        $query_destination='SELECT IDENTITY (a.destination) FROM HearWeGoHearWeGoBundle:Article a WHERE a.id=:id';
        $destination_id=$this->getEntityManager()->createQuery($query_destination)->setParameter('id',$id)->getOneOrNullResult();
        $query='SELECT a FROM HearWeGoHearWeGoBundle:Article a WHERE (IDENTITY(a.destination)=:destination_id AND a.id!=:id)';
        return $this->getEntityManager()->createQuery($query)->setParameters(array('destination_id'=>$destination_id,'id'=>$id))->getResult();
    }

    public function queryAll()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('HearWeGoHearWeGoBundle:Article','a')
            ->orderBy('a.createdAt','DESC')
            ->getQuery();
    }
}
