<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllDesc()
    {
        return $this->getEntityManager()->createQuery('SELECT c FROM HearWeGoHearWeGoBundle:Comment c ORDER BY c.createdAt DESC')->getResult();
    }
}
