<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()->createQuery('SELECT d FROM HearWeGoHearWeGoBundle:Destination d')->getResult();
    }

    public function findByName($name)
    {
        return $this->getEntityManager()->createQuery('SELECT d FROM HearWeGoHearWeGoBundle:Destination d WHERE d.name=:name')->setParameter('name',$name)->getOneOrNullResult();
    }

    public function findDestinationWithoutAudio()
    {
        $query='SELECT d FROM HearWeGoHearWeGoBundle:Destination d WHERE d NOT IN (SELECT IDENTITY (a.destination) FROM HearWeGoHearWeGoBundle:Audio a)';
        return $this->getEntityManager()->createQuery($query)->getResult();
    }
}
