<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function getRoleUser(){
        $roleUser = 'ROLE_USER';
        $query = $this->getEntityManager()->createQuery(
            'SELECT r FROM HearWeGoHearWeGoBundle:Role r WHERE r.role=:role_user'
        )->setParameter('role_user', $roleUser);
        return $query->getOneOrNullResult();
    }
}
