<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    public function findNewTour( $num ){
        $query = $this->getEntityManager()->createQuery(
            'SELECT t FROM HearWeGoHearWeGoBundle:Tour t ORDER BY t.createdAt DESC'
        )->setMaxResults( $num );
        return $query->getResult();
    }
}
