<?php

namespace HearWeGo\HearWeGoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{

    public function findNewTour( $num ){
        $date = new \DateTime();
        $query = $this->getEntityManager()->createQuery(
            'SELECT t FROM HearWeGoHearWeGoBundle:Tour t WHERE t.startdate > :date AND t.status = 1 ORDER BY t.createdAt DESC'
        )->setParameter('date', $date)->setMaxResults( $num );
        return $query->getResult();
    }

    public function findSaleTour( $num ){
        $date = new \DateTime();
        $query = $this->getEntityManager()->createQuery(
            'SELECT t FROM HearWeGoHearWeGoBundle:Tour t WHERE t.startdate > :date AND t.status = 1 ORDER BY t.discount DESC'
        )->setParameter('date', $date)->setMaxResults( $num );
        return $query->getResult();
    }

    public function findCompanyTours( $companyId ){
        $rsm = new ResultSetMapping();
        $query =$this->getEntityManager()->createNativeQuery(
            'SELECT * FROM tour WHERE company_id = ? ORDER BY created_at DESC',$rsm
        )->setParameter(1,$companyId);
        return $query->getResult();
    }
}
